version: "3.8"
services:
  react-node-app:
    image: ${IMAGE}
    ports:
      - 3000:3080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
